### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ktangsali**
# Modulus Pull Request

## Description
Updates the Readme

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus-sym/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/modulus-sym/blob/main/CHANGELOG.md) is up to date with these changes.
- [ ] An [issue](https://github.com/NVIDIA/modulus-sym/issues) is linked to this pull request.

### CODE REVIEW

**Review by ram-cherukuri — APPROVED** [review]
Can we add this back once the example is live?

**Comment by ktangsali** [comment]
> Can we add this back once the example is live?

Yes, precisely. Since the example is not live yet, the link will not work. I will be sure to add this back once live.

**Pull request merged**
